Added test + implementation for current relations
ArchivesNationalesFR/rico-converter pull request #73
Opened 2024-10-18 15:48 UTC by tfrancart

2024-10-22 16:47 UTC, florenceclavaud commented on ricoconverter/ricoconverter-convert/src/main/resources/xslt_eac/eac2rico-relations.xslt
> +			<shortcutIfSubjectIsSourceOfRelation_current>rico:hasDirectSubordinate</shortcutIfSubjectIsSourceOfRelation_current>
Yes, and there should also be something like shortcutIfSubjectIsSourceOfRelation_past with value rico:hadSubordinate (and the second one, with value rico:wasSubordinateTo)

2024-10-22 16:51 UTC, florenceclavaud commented on ricoconverter/ricoconverter-convert/src/main/resources/xslt_eac/eac2rico-relations.xslt
> +			<shortcutIfSubjectIsSourceOfRelation_current>rico:isOrWasControllerOf</shortcutIfSubjectIsSourceOfRelation_current>
Nothing should change here. We do not have wasControllerOf or isControllerOf in RiC-O for now

2024-10-22 16:52 UTC, florenceclavaud commented on ricoconverter/ricoconverter-convert/src/main/resources/xslt_eac/eac2rico-relations.xslt
IMHO a few details should be changed in this file; see my specific comments

2024-10-22 16:56 UTC, florenceclavaud commented on ricoconverter/ricoconverter-convert/src/main/resources/xslt_eac/eac2rico.xslt
> +					<xsl:value-of select="$HIERARCHICAL_RELATION_CONFIG/*[local-name() = normalize-space($type)]/shortcutIfSubjectIsSourceOfRelation" />
or `<xsl:value-of select="$HIERARCHICAL_RELATION_CONFIG/*[local-name() = normalize-space($type)]/shortcutIfSubjectIsSourceOfRelation_past" />`? See my comment on the eac2rico-relations.xslt

2024-10-22 17:09 UTC, florenceclavaud reviewed
I have added a few comments to the changes in the XSLT files. IMHO a few lines are missing (to take into account the cases of past relations, which correspond to other object properties, that are not exactly shortcuts but were added to RiC-O 1.0). Also, we should probably add other unit tests, and change some existing ones (I can help do this). Finally, even if in the AnF, such relations _always_ have a date, there may be cases elsewhere where they are not dated, and we could take them into account too - and generate what is in fact already generated woth Ric-O Converter 2.

2024-10-29 16:08 UTC, tfrancart commented
- Si date de début mais pas de date de fin, utiliser la relation "current"
- Si date de début + date de fin, utiliser une relation "past"
- Si aucune date, rester sur la propriété générique

2024-10-30 09:39 UTC, tfrancart commented
@florenceclavaud I did the "past" relation implementation. Can you please review and also review the unit tests, and add unit tests if you feel some cases of relations with dates are missing ? thanks

2024-10-30 16:22 UTC, florenceclavaud commented on ricoconverter/ricoconverter-convert/src/test/resources/eac2rico/_37emptyDates/expected.xml
> +      <rico:hadSubordinate rdf:resource="agent/111111" />
It should be rico:hasDirectSubordinate here (in the input file there is no end date for the relation, so we consider it is current).

2024-10-30 16:25 UTC, florenceclavaud requested changes
Everything is Ok except in the last file (expected file in the _37emptyDates folder) - see my comment. And so, I am also realizing that there may be eac:toDate or eac:fromDate that are empty; the XSLT does not take this into acccount I think.

2024-10-30 16:29 UTC, florenceclavaud commented
> * Si date de début mais pas de date de fin, utiliser la relation "current"
> 
>     * Si date de début + date de fin, utiliser une relation "past"
> 
>     * Si aucune date, rester sur la propriété générique

Ou plutôt : si date de début existe et est non vide, mais pas de date de fin ou date de fin vide, on utilise la relation "current"
Si date de début et date de fin non vides, on utilise la relation "past"
Si pas de dates du tout, ou si fromDate et toDate sont vides, on reste sur la propriété générique

2024-11-07 12:01 UTC, tfrancart commented
Note : to determine that the relation is in the past, we could even avoid testing on the presence of the fromDate attribute. The only presence of the `toDate` attribute is sufficient.

2024-11-19 17:47 UTC, florenceclavaud approved these changes
Everything OK

2024-11-20 11:47 UTC, merged